title: Behind The Poster
description: A website dedicated to the typographical decisions on movie posters.
header_text: Movie Posters
footer_text: Copyright 2020 Laura Evans
header_feature_image: ../uploads/behind-the-poster-banner-image.png
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items: []
