title: Behind The Poster
description: A website dedicated to the typographical decisions on movie posters.
header_text: ""
footer_text: Copyright 2020 Laura Evans
header_feature_image: ../uploads/behind-the-poster-banner-image-2.png
bannerheight: 20vmax
logo: ../uploads/behind-the-poster-logo.png
favicon: ../uploads/png-logo.png
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - name: Get To Know Me
    siteurl: /aboutme
    tab: true
